export const checkdetailColumns = [
    {
        title: "排名",
        dataIndex: "rank",
        key: "rank",
    },
    {
        title: "稽核类型",
        dataIndex: "type",
        key: "type",
        width: 150,
        filters: [
            {
                text: "电费",
                value: "电费",
            },
            {
                text: "铁塔服务费",
                value: "铁塔服务费",
            },
            {
                text: "租费",
                value: "租费",
            },
        ],
        onFilter: (value, record) => record.type.indexOf(value) === 0,
        // ellipsis: true,
    },
    {
        title: "省份",
        dataIndex: "province",
        key: "province",
        // ellipsis: true,
    },
    {
        title: "9-10分",
        dataIndex: "ninetoten",
        key: "ninetoten",
        // defaultSortOrder: "descend",
        sorter: (a, b) => a.ninetoten - b.ninetoten,
        ellipsis: true,
    },
    {
        title: "8-9分",
        dataIndex: "eightto9",
        key: "eightto9",
        sorter: (a, b) => a.eightto9 - b.eightto9,
        ellipsis: true,
    },
    {
        title: "6-8分",
        dataIndex: "sixto8",
        key: "sixto8",
        sorter: (a, b) => a.sixto8 - b.sixto8,
        ellipsis: true,
    },
    {
        title: "0-6分",
        dataIndex: "zerotosix",
        key: "zerotosix",
        sorter: (a, b) => a.zerotosix - b.zerotosix,
        ellipsis: true,
    },
    {
        title: "总量",
        dataIndex: "total",
        key: "total",
        sorter: (a, b) => a.total - b.total,
    },
    {
        title: "通过数",
        dataIndex: "passtotal",
        key: "passtotal",
        sorter: (a, b) => a.passtotal - b.passtotal,
    },
    {
        title: "未通过数",
        dataIndex: "notpass",
        key: "notpass",
        sorter: (a, b) => a.notpass - b.notpass,
        scopedSlots: { customRender: "notpass" },
    },
    {
        title: "未通过率",
        dataIndex: "notpassper",
        key: "notpassper",
        sorter: (a, b) => a.notpassper - b.notpassper,
        scopedSlots: { customRender: "notpassper" },
    },
];
